# Site settings
title: Index
#email: your-email@domain.com
description: "Things, stuff, random stuff, arbitrary stuff and things."
#twitter_username: MyFakeAcc
#github_username: Argon-
excerpt_separator: "<!-- more -->"

# Build settings
safe: true
destination: _site_remote
baseurl: "http://w3studi.informatik.uni-stuttgart.de/~zieglejn/index" 
markdown: kramdown
highlighter: pygments
encoding: utf-8
permalink: /:year/:month/:day/:title/
